/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#002e6a",
        "primary-container": "#4d8eff",
        "surface-bright": "#39393b",
        "background": "#131315",
        "inverse-surface": "#e5e1e4",
        "surface-variant": "#353437",
        "on-tertiary-fixed": "#261a00",
        "primary-fixed": "#d8e2ff",
        "secondary-container": "#571bc1",
        "tertiary-container": "#b88900",
        "surface-container-high": "#2a2a2c",
        "inverse-on-surface": "#313032",
        "surface-container-low": "#1c1b1d",
        "surface-tint": "#adc6ff",
        "on-primary-fixed": "#001a42",
        "error": "#ffb4ab",
        "secondary": "#d0bcff",
        "secondary-fixed": "#e9ddff",
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary-container": "#372700",
        "outline-variant": "#424754",
        "on-tertiary": "#402d00",
        "surface-dim": "#131315",
        "on-tertiary-fixed-variant": "#5c4300",
        "on-error": "#690005",
        "inverse-primary": "#005ac2",
        "on-primary-fixed-variant": "#004395",
        "tertiary": "#f9bd22",
        "tertiary-fixed-dim": "#f9bd22",
        "on-secondary-container": "#c4abff",
        "surface-container": "#201f21",
        "surface": "#131315",
        "primary": "#adc6ff",
        "outline": "#8c909f",
        "secondary-fixed-dim": "#d0bcff",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0e0e10",
        "surface-container-highest": "#353437",
        "on-background": "#e5e1e4",
        "on-surface-variant": "#c2c6d6",
        "on-secondary-fixed": "#23005c",
        "on-surface": "#e5e1e4",
        "tertiary-fixed": "#ffdf9f",
        "on-secondary": "#3c0091",
        "on-secondary-fixed-variant": "#5516be",
        "on-primary-container": "#00285d",
        "error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
  ],
}
